/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns server health status including database connectivity.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dealerships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all dealerships
         * @description Returns all dealerships in the system.
         */
        get: operations["listDealerships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List vehicles with filters
         * @description Returns a paginated, filterable list of vehicles.
         */
        get: operations["listVehicles"];
        put?: never;
        /**
         * Create a new vehicle
         * @description Adds a new vehicle to the inventory.
         */
        post: operations["createVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export filtered vehicles as CSV
         * @description Exports all vehicles matching the given filters as a CSV file. No pagination — exports all matching records (max 10,000).
         */
        get: operations["exportVehicles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get vehicle details
         * @description Returns a single vehicle with its action history.
         */
        get: operations["getVehicle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List actions for a vehicle
         * @description Returns all actions logged for a specific vehicle, ordered by creation date descending.
         */
        get: operations["listVehicleActions"];
        put?: never;
        /**
         * Log an action for a vehicle
         * @description Creates a new action entry for a vehicle. Actions are append-only and cannot be modified or deleted.
         */
        post: operations["createVehicleAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard summary
         * @description Returns aggregated inventory statistics including aging stock counts.
         */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "healthy" | "unhealthy";
            /** @example 1.0.0 */
            version: string;
            /** @example 2h30m */
            uptime: string;
            /** @enum {string} */
            database: "connected" | "disconnected";
            /** Format: date-time */
            timestamp: string;
        };
        Dealership: {
            /** Format: uuid */
            id: string;
            name: string;
            location?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Vehicle: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            dealership_id: string;
            make: string;
            model: string;
            year: number;
            vin: string;
            /** Format: double */
            price?: number;
            /** @enum {string} */
            status: "available" | "sold" | "reserved";
            /** Format: date-time */
            stocked_at: string;
            /** @description Computed field — number of days since stocked_at */
            days_in_stock?: number;
            /** @description Computed field — true if days_in_stock > 90 */
            is_aging?: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Action history, included in vehicle detail response */
            actions?: components["schemas"]["VehicleAction"][];
        };
        VehicleAction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            vehicle_id: string;
            /** @enum {string} */
            action_type: "price_reduction" | "transfer" | "auction" | "marketing" | "wholesale" | "custom";
            notes?: string;
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateVehicleActionRequest: {
            /** @enum {string} */
            action_type: "price_reduction" | "transfer" | "auction" | "marketing" | "wholesale" | "custom";
            notes?: string;
            created_by: string;
        };
        PaginatedVehicles: {
            items: components["schemas"]["Vehicle"][];
            /** @description Total number of matching vehicles */
            total: number;
            /** @description Current page number */
            page: number;
            /** @description Number of items per page */
            page_size: number;
            /** @description Total number of pages */
            total_pages: number;
        };
        DashboardSummary: {
            total_vehicles: number;
            aging_vehicles: number;
            /** Format: double */
            average_days_in_stock: number;
            /** @description Number of vehicle actions created in the last 30 days */
            actions_this_month: number;
            by_make: components["schemas"]["MakeSummary"][];
            by_status: components["schemas"]["StatusSummary"][];
        };
        MakeSummary: {
            make: string;
            count: number;
            aging_count: number;
        };
        StatusSummary: {
            status: string;
            count: number;
        };
        CreateVehicleRequest: {
            /** Format: uuid */
            dealership_id: string;
            make: string;
            model: string;
            year: number;
            vin: string;
            /** Format: double */
            price?: number;
            /** @enum {string} */
            status: "available" | "sold" | "reserved";
            /** Format: date-time */
            stocked_at?: string;
        };
        ErrorResponse: {
            /** @description HTTP status code */
            code: number;
            /** @description Human-readable error message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Server is unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listDealerships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of dealerships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dealership"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listVehicles: {
        parameters: {
            query?: {
                /** @description Filter by dealership ID */
                dealership_id?: string;
                /** @description Filter by vehicle make */
                make?: string;
                /** @description Filter by vehicle model */
                model?: string;
                /** @description Filter by vehicle status */
                status?: "available" | "sold" | "reserved";
                /** @description If true, only return vehicles stocked for more than 90 days */
                aging?: boolean;
                /** @description Column to sort by */
                sort_by?: "stocked_at" | "price" | "year" | "make";
                /** @description Sort order */
                order?: "asc" | "desc";
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Number of items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of vehicles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVehicles"];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleRequest"];
            };
        };
        responses: {
            /** @description Vehicle created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description Invalid request body or validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A vehicle with this VIN already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exportVehicles: {
        parameters: {
            query?: {
                dealership_id?: string;
                make?: string;
                model?: string;
                status?: "available" | "sold" | "reserved";
                aging?: boolean;
                sort_by?: "stocked_at" | "price" | "year" | "make";
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Invalid query parameters or export limit exceeded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vehicle UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description Vehicle not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listVehicleActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vehicle UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of vehicle actions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleAction"][];
                };
            };
            /** @description Vehicle not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createVehicleAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vehicle UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleActionRequest"];
            };
        };
        responses: {
            /** @description Action created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleAction"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Vehicle not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
