// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateVehicleActionRequestActionType.
const (
	CreateVehicleActionRequestActionTypeAuction        CreateVehicleActionRequestActionType = "auction"
	CreateVehicleActionRequestActionTypeCustom         CreateVehicleActionRequestActionType = "custom"
	CreateVehicleActionRequestActionTypeMarketing      CreateVehicleActionRequestActionType = "marketing"
	CreateVehicleActionRequestActionTypePriceReduction CreateVehicleActionRequestActionType = "price_reduction"
	CreateVehicleActionRequestActionTypeTransfer       CreateVehicleActionRequestActionType = "transfer"
	CreateVehicleActionRequestActionTypeWholesale      CreateVehicleActionRequestActionType = "wholesale"
)

// Valid indicates whether the value is a known member of the CreateVehicleActionRequestActionType enum.
func (e CreateVehicleActionRequestActionType) Valid() bool {
	switch e {
	case CreateVehicleActionRequestActionTypeAuction:
		return true
	case CreateVehicleActionRequestActionTypeCustom:
		return true
	case CreateVehicleActionRequestActionTypeMarketing:
		return true
	case CreateVehicleActionRequestActionTypePriceReduction:
		return true
	case CreateVehicleActionRequestActionTypeTransfer:
		return true
	case CreateVehicleActionRequestActionTypeWholesale:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseDatabase.
const (
	Connected    HealthResponseDatabase = "connected"
	Disconnected HealthResponseDatabase = "disconnected"
)

// Valid indicates whether the value is a known member of the HealthResponseDatabase enum.
func (e HealthResponseDatabase) Valid() bool {
	switch e {
	case Connected:
		return true
	case Disconnected:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Defines values for VehicleStatus.
const (
	VehicleStatusAvailable VehicleStatus = "available"
	VehicleStatusReserved  VehicleStatus = "reserved"
	VehicleStatusSold      VehicleStatus = "sold"
)

// Valid indicates whether the value is a known member of the VehicleStatus enum.
func (e VehicleStatus) Valid() bool {
	switch e {
	case VehicleStatusAvailable:
		return true
	case VehicleStatusReserved:
		return true
	case VehicleStatusSold:
		return true
	default:
		return false
	}
}

// Defines values for VehicleActionActionType.
const (
	VehicleActionActionTypeAuction        VehicleActionActionType = "auction"
	VehicleActionActionTypeCustom         VehicleActionActionType = "custom"
	VehicleActionActionTypeMarketing      VehicleActionActionType = "marketing"
	VehicleActionActionTypePriceReduction VehicleActionActionType = "price_reduction"
	VehicleActionActionTypeTransfer       VehicleActionActionType = "transfer"
	VehicleActionActionTypeWholesale      VehicleActionActionType = "wholesale"
)

// Valid indicates whether the value is a known member of the VehicleActionActionType enum.
func (e VehicleActionActionType) Valid() bool {
	switch e {
	case VehicleActionActionTypeAuction:
		return true
	case VehicleActionActionTypeCustom:
		return true
	case VehicleActionActionTypeMarketing:
		return true
	case VehicleActionActionTypePriceReduction:
		return true
	case VehicleActionActionTypeTransfer:
		return true
	case VehicleActionActionTypeWholesale:
		return true
	default:
		return false
	}
}

// Defines values for ListVehiclesParamsStatus.
const (
	ListVehiclesParamsStatusAvailable ListVehiclesParamsStatus = "available"
	ListVehiclesParamsStatusReserved  ListVehiclesParamsStatus = "reserved"
	ListVehiclesParamsStatusSold      ListVehiclesParamsStatus = "sold"
)

// Valid indicates whether the value is a known member of the ListVehiclesParamsStatus enum.
func (e ListVehiclesParamsStatus) Valid() bool {
	switch e {
	case ListVehiclesParamsStatusAvailable:
		return true
	case ListVehiclesParamsStatusReserved:
		return true
	case ListVehiclesParamsStatusSold:
		return true
	default:
		return false
	}
}

// Defines values for ListVehiclesParamsSortBy.
const (
	Make      ListVehiclesParamsSortBy = "make"
	Price     ListVehiclesParamsSortBy = "price"
	StockedAt ListVehiclesParamsSortBy = "stocked_at"
	Year      ListVehiclesParamsSortBy = "year"
)

// Valid indicates whether the value is a known member of the ListVehiclesParamsSortBy enum.
func (e ListVehiclesParamsSortBy) Valid() bool {
	switch e {
	case Make:
		return true
	case Price:
		return true
	case StockedAt:
		return true
	case Year:
		return true
	default:
		return false
	}
}

// Defines values for ListVehiclesParamsOrder.
const (
	Asc  ListVehiclesParamsOrder = "asc"
	Desc ListVehiclesParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListVehiclesParamsOrder enum.
func (e ListVehiclesParamsOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// CreateVehicleActionRequest defines model for CreateVehicleActionRequest.
type CreateVehicleActionRequest struct {
	ActionType CreateVehicleActionRequestActionType `json:"action_type"`
	CreatedBy  string                               `json:"created_by"`
	Notes      *string                              `json:"notes,omitempty"`
}

// CreateVehicleActionRequestActionType defines model for CreateVehicleActionRequest.ActionType.
type CreateVehicleActionRequestActionType string

// DashboardSummary defines model for DashboardSummary.
type DashboardSummary struct {
	AgingVehicles      int             `json:"aging_vehicles"`
	AverageDaysInStock float64         `json:"average_days_in_stock"`
	ByMake             []MakeSummary   `json:"by_make"`
	ByStatus           []StatusSummary `json:"by_status"`
	TotalVehicles      int             `json:"total_vehicles"`
}

// Dealership defines model for Dealership.
type Dealership struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Location  *string            `json:"location,omitempty"`
	Name      string             `json:"name"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code HTTP status code
	Code int `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Database  HealthResponseDatabase `json:"database"`
	Status    HealthResponseStatus   `json:"status"`
	Timestamp time.Time              `json:"timestamp"`
	Uptime    string                 `json:"uptime"`
	Version   string                 `json:"version"`
}

// HealthResponseDatabase defines model for HealthResponse.Database.
type HealthResponseDatabase string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// MakeSummary defines model for MakeSummary.
type MakeSummary struct {
	AgingCount int    `json:"aging_count"`
	Count      int    `json:"count"`
	Make       string `json:"make"`
}

// PaginatedVehicles defines model for PaginatedVehicles.
type PaginatedVehicles struct {
	Items []Vehicle `json:"items"`

	// Page Current page number
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"page_size"`

	// Total Total number of matching vehicles
	Total int `json:"total"`

	// TotalPages Total number of pages
	TotalPages int `json:"total_pages"`
}

// StatusSummary defines model for StatusSummary.
type StatusSummary struct {
	Count  int    `json:"count"`
	Status string `json:"status"`
}

// Vehicle defines model for Vehicle.
type Vehicle struct {
	// Actions Action history, included in vehicle detail response
	Actions   *[]VehicleAction `json:"actions,omitempty"`
	CreatedAt time.Time        `json:"created_at"`

	// DaysInStock Computed field — number of days since stocked_at
	DaysInStock  *int               `json:"days_in_stock,omitempty"`
	DealershipId openapi_types.UUID `json:"dealership_id"`
	Id           openapi_types.UUID `json:"id"`

	// IsAging Computed field — true if days_in_stock > 90
	IsAging   *bool         `json:"is_aging,omitempty"`
	Make      string        `json:"make"`
	Model     string        `json:"model"`
	Price     *float64      `json:"price,omitempty"`
	Status    VehicleStatus `json:"status"`
	StockedAt time.Time     `json:"stocked_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	Vin       string        `json:"vin"`
	Year      int           `json:"year"`
}

// VehicleStatus defines model for Vehicle.Status.
type VehicleStatus string

// VehicleAction defines model for VehicleAction.
type VehicleAction struct {
	ActionType VehicleActionActionType `json:"action_type"`
	CreatedAt  time.Time               `json:"created_at"`
	CreatedBy  string                  `json:"created_by"`
	Id         openapi_types.UUID      `json:"id"`
	Notes      *string                 `json:"notes,omitempty"`
	VehicleId  openapi_types.UUID      `json:"vehicle_id"`
}

// VehicleActionActionType defines model for VehicleAction.ActionType.
type VehicleActionActionType string

// ListVehiclesParams defines parameters for ListVehicles.
type ListVehiclesParams struct {
	// DealershipId Filter by dealership ID
	DealershipId *openapi_types.UUID `form:"dealership_id,omitempty" json:"dealership_id,omitempty"`

	// Make Filter by vehicle make
	Make *string `form:"make,omitempty" json:"make,omitempty"`

	// Model Filter by vehicle model
	Model *string `form:"model,omitempty" json:"model,omitempty"`

	// Status Filter by vehicle status
	Status *ListVehiclesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Aging If true, only return vehicles stocked for more than 90 days
	Aging *bool `form:"aging,omitempty" json:"aging,omitempty"`

	// SortBy Column to sort by
	SortBy *ListVehiclesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// Order Sort order
	Order *ListVehiclesParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// Page Page number (1-indexed)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListVehiclesParamsStatus defines parameters for ListVehicles.
type ListVehiclesParamsStatus string

// ListVehiclesParamsSortBy defines parameters for ListVehicles.
type ListVehiclesParamsSortBy string

// ListVehiclesParamsOrder defines parameters for ListVehicles.
type ListVehiclesParamsOrder string

// CreateVehicleActionJSONRequestBody defines body for CreateVehicleAction for application/json ContentType.
type CreateVehicleActionJSONRequestBody = CreateVehicleActionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get dashboard summary
	// (GET /api/v1/dashboard/summary)
	GetDashboardSummary(w http.ResponseWriter, r *http.Request)
	// List all dealerships
	// (GET /api/v1/dealerships)
	ListDealerships(w http.ResponseWriter, r *http.Request)
	// List vehicles with filters
	// (GET /api/v1/vehicles)
	ListVehicles(w http.ResponseWriter, r *http.Request, params ListVehiclesParams)
	// Get vehicle details
	// (GET /api/v1/vehicles/{id})
	GetVehicle(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List actions for a vehicle
	// (GET /api/v1/vehicles/{id}/actions)
	ListVehicleActions(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Log an action for a vehicle
	// (POST /api/v1/vehicles/{id}/actions)
	CreateVehicleAction(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get dashboard summary
// (GET /api/v1/dashboard/summary)
func (_ Unimplemented) GetDashboardSummary(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all dealerships
// (GET /api/v1/dealerships)
func (_ Unimplemented) ListDealerships(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List vehicles with filters
// (GET /api/v1/vehicles)
func (_ Unimplemented) ListVehicles(w http.ResponseWriter, r *http.Request, params ListVehiclesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get vehicle details
// (GET /api/v1/vehicles/{id})
func (_ Unimplemented) GetVehicle(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List actions for a vehicle
// (GET /api/v1/vehicles/{id}/actions)
func (_ Unimplemented) ListVehicleActions(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log an action for a vehicle
// (POST /api/v1/vehicles/{id}/actions)
func (_ Unimplemented) CreateVehicleAction(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDashboardSummary operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardSummary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDealerships operation middleware
func (siw *ServerInterfaceWrapper) ListDealerships(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDealerships(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVehicles operation middleware
func (siw *ServerInterfaceWrapper) ListVehicles(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVehiclesParams

	// ------------- Optional query parameter "dealership_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "dealership_id", r.URL.Query(), &params.DealershipId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dealership_id", Err: err})
		return
	}

	// ------------- Optional query parameter "make" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "make", r.URL.Query(), &params.Make, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "make", Err: err})
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", r.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "aging" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "aging", r.URL.Query(), &params.Aging, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "aging", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_by", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVehicles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVehicle operation middleware
func (siw *ServerInterfaceWrapper) GetVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVehicle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVehicleActions operation middleware
func (siw *ServerInterfaceWrapper) ListVehicleActions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVehicleActions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVehicleAction operation middleware
func (siw *ServerInterfaceWrapper) CreateVehicleAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVehicleAction(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/dashboard/summary", wrapper.GetDashboardSummary)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/dealerships", wrapper.ListDealerships)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/vehicles", wrapper.ListVehicles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/vehicles/{id}", wrapper.GetVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/vehicles/{id}/actions", wrapper.ListVehicleActions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/vehicles/{id}/actions", wrapper.CreateVehicleAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

type GetDashboardSummaryRequestObject struct {
}

type GetDashboardSummaryResponseObject interface {
	VisitGetDashboardSummaryResponse(w http.ResponseWriter) error
}

type GetDashboardSummary200JSONResponse DashboardSummary

func (response GetDashboardSummary200JSONResponse) VisitGetDashboardSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDashboardSummary500JSONResponse ErrorResponse

func (response GetDashboardSummary500JSONResponse) VisitGetDashboardSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListDealershipsRequestObject struct {
}

type ListDealershipsResponseObject interface {
	VisitListDealershipsResponse(w http.ResponseWriter) error
}

type ListDealerships200JSONResponse []Dealership

func (response ListDealerships200JSONResponse) VisitListDealershipsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDealerships500JSONResponse ErrorResponse

func (response ListDealerships500JSONResponse) VisitListDealershipsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListVehiclesRequestObject struct {
	Params ListVehiclesParams
}

type ListVehiclesResponseObject interface {
	VisitListVehiclesResponse(w http.ResponseWriter) error
}

type ListVehicles200JSONResponse PaginatedVehicles

func (response ListVehicles200JSONResponse) VisitListVehiclesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListVehicles400JSONResponse ErrorResponse

func (response ListVehicles400JSONResponse) VisitListVehiclesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListVehicles500JSONResponse ErrorResponse

func (response ListVehicles500JSONResponse) VisitListVehiclesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicleRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetVehicleResponseObject interface {
	VisitGetVehicleResponse(w http.ResponseWriter) error
}

type GetVehicle200JSONResponse Vehicle

func (response GetVehicle200JSONResponse) VisitGetVehicleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicle404JSONResponse ErrorResponse

func (response GetVehicle404JSONResponse) VisitGetVehicleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetVehicle500JSONResponse ErrorResponse

func (response GetVehicle500JSONResponse) VisitGetVehicleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListVehicleActionsRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ListVehicleActionsResponseObject interface {
	VisitListVehicleActionsResponse(w http.ResponseWriter) error
}

type ListVehicleActions200JSONResponse []VehicleAction

func (response ListVehicleActions200JSONResponse) VisitListVehicleActionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListVehicleActions404JSONResponse ErrorResponse

func (response ListVehicleActions404JSONResponse) VisitListVehicleActionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListVehicleActions500JSONResponse ErrorResponse

func (response ListVehicleActions500JSONResponse) VisitListVehicleActionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateVehicleActionRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *CreateVehicleActionJSONRequestBody
}

type CreateVehicleActionResponseObject interface {
	VisitCreateVehicleActionResponse(w http.ResponseWriter) error
}

type CreateVehicleAction201JSONResponse VehicleAction

func (response CreateVehicleAction201JSONResponse) VisitCreateVehicleActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateVehicleAction400JSONResponse ErrorResponse

func (response CreateVehicleAction400JSONResponse) VisitCreateVehicleActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateVehicleAction404JSONResponse ErrorResponse

func (response CreateVehicleAction404JSONResponse) VisitCreateVehicleActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateVehicleAction500JSONResponse ErrorResponse

func (response CreateVehicleAction500JSONResponse) VisitCreateVehicleActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth503JSONResponse HealthResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get dashboard summary
	// (GET /api/v1/dashboard/summary)
	GetDashboardSummary(ctx context.Context, request GetDashboardSummaryRequestObject) (GetDashboardSummaryResponseObject, error)
	// List all dealerships
	// (GET /api/v1/dealerships)
	ListDealerships(ctx context.Context, request ListDealershipsRequestObject) (ListDealershipsResponseObject, error)
	// List vehicles with filters
	// (GET /api/v1/vehicles)
	ListVehicles(ctx context.Context, request ListVehiclesRequestObject) (ListVehiclesResponseObject, error)
	// Get vehicle details
	// (GET /api/v1/vehicles/{id})
	GetVehicle(ctx context.Context, request GetVehicleRequestObject) (GetVehicleResponseObject, error)
	// List actions for a vehicle
	// (GET /api/v1/vehicles/{id}/actions)
	ListVehicleActions(ctx context.Context, request ListVehicleActionsRequestObject) (ListVehicleActionsResponseObject, error)
	// Log an action for a vehicle
	// (POST /api/v1/vehicles/{id}/actions)
	CreateVehicleAction(ctx context.Context, request CreateVehicleActionRequestObject) (CreateVehicleActionResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDashboardSummary operation middleware
func (sh *strictHandler) GetDashboardSummary(w http.ResponseWriter, r *http.Request) {
	var request GetDashboardSummaryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDashboardSummary(ctx, request.(GetDashboardSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDashboardSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDashboardSummaryResponseObject); ok {
		if err := validResponse.VisitGetDashboardSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDealerships operation middleware
func (sh *strictHandler) ListDealerships(w http.ResponseWriter, r *http.Request) {
	var request ListDealershipsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDealerships(ctx, request.(ListDealershipsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDealerships")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDealershipsResponseObject); ok {
		if err := validResponse.VisitListDealershipsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVehicles operation middleware
func (sh *strictHandler) ListVehicles(w http.ResponseWriter, r *http.Request, params ListVehiclesParams) {
	var request ListVehiclesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVehicles(ctx, request.(ListVehiclesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVehicles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVehiclesResponseObject); ok {
		if err := validResponse.VisitListVehiclesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVehicle operation middleware
func (sh *strictHandler) GetVehicle(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetVehicleRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVehicle(ctx, request.(GetVehicleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVehicle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVehicleResponseObject); ok {
		if err := validResponse.VisitGetVehicleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVehicleActions operation middleware
func (sh *strictHandler) ListVehicleActions(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ListVehicleActionsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVehicleActions(ctx, request.(ListVehicleActionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVehicleActions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVehicleActionsResponseObject); ok {
		if err := validResponse.VisitListVehicleActionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVehicleAction operation middleware
func (sh *strictHandler) CreateVehicleAction(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request CreateVehicleActionRequestObject

	request.Id = id

	var body CreateVehicleActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVehicleAction(ctx, request.(CreateVehicleActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVehicleAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVehicleActionResponseObject); ok {
		if err := validResponse.VisitCreateVehicleActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
